apps/blog/urls.py
from django.conf.urls import include, url

from .views import BlogIndexView, BlogDetailView, BlogWriteupIndexView, BlogWriteupDetailView

app_name="blog"

writeuppatterns =[
	url(r'^$', BlogWriteupIndexView.as_view(), name='writeup-index'),
	url(r'^(?P<slug>.*)/$', BlogWriteupDetailView.as_view(), name='writeup-detail')
]

urlpatterns =[
	url(r'^blog/$', BlogIndexView.as_view(), name='index'),
	url(r'^blog_writeup/', include(writeuppatterns))
]

project/urls.py
from django.contrib import admin
from django.conf.urls import include, url

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
]

urlpatterns += [
    url(r'', include('apps.blog.urls', namespace='blog')),
	url(r'', include('apps.flatpage.urls', namespace='flatpage')),
    url(r'', include('apps.project.urls', namespace='project')),
    url(r'', include('apps.writeup.urls', namespace='writeup'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/partials/footer.html
<footer class="main">
	<p class="copyright hpc">© 2022<span class="copyright-brand ml2">Darryl Smith II.</span></p>
	<ul class="social hpc">
		<a href="https://twitter.com/_darrylmichael" target="_blank">
			<i class="fab fa-twitter-square"></i>
		</a>
		<a href="https://www.facebook.com/darrylmsmithii" target="_blank"><i class="fab fa-facebook-square"></i></a>
		<a href="https://github.com/dmsii" target="_blank"><i class="fab fa-github-square"></i></a>
	</ul>
</footer>

templates/partials/nav_main.html
<nav class="main bg-white shadow-sm">
	<a class="brand hpc" href="{% url 'flatpage:index' %}">Darryl Smith II</a>
	<ul>
		<li><a class="link" href="{% url 'project:index' %}">Projects</a></li>
		<li><a class="link" href="{% url 'blog:index' %}">Blog</a></li>
	</ul>
</nav>

templates/partials/project_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="{% url 'flatpage:index' %}">Darryl Smith II</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	  <span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNav">
	  <ul class="navbar-nav">
		<li class="nav-item">
		  <a class="nav-link" href="{% url 'project:index' %}">Projects</a>
		</li>
		<li class="nav-item">
		  <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
		</li>
	  </ul>
	</div>
  </nav>