apps/project/urls.py
from django.conf.urls import include, url

from .views import ProjectIndexView, ProjectDetailView

app_name="project"

urlpatterns =[
	url(r'^project/$', ProjectIndexView.as_view(), name='index'),
	url(r'^project/(?P<slug>.*)/$', ProjectDetailView.as_view(), name='detail')
]

project/urls.py
from django.contrib import admin
from django.conf.urls import include, url

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
]

urlpatterns += [
    url(r'', include('apps.blog.urls', namespace='blog')),
	url(r'', include('apps.flatpage.urls', namespace='flatpage')),
    url(r'', include('apps.project.urls', namespace='project')),
    url(r'', include('apps.writeup.urls', namespace='writeup'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/project/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from taggit.managers import TaggableManager


# Create your models here.
class Project(models.Model):
    def lorem_default():
        return "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi eos laboriosam et eius."

    brandname     = models.CharField(max_length=200, null=True)
    recap         = models.TextField(null=True)

    brandlogo     = models.ImageField(upload_to='project/images/', null=True)
    brandtypeface = models.ImageField(upload_to='project/images/', null=True)

    text          = models.TextField(null=True, blank=True)
    author        = models.ForeignKey(User, on_delete=models.CASCADE)

    title         = models.CharField(max_length=200, null=True)
    description   = models.CharField(max_length=400, null=True)

    tags = TaggableManager(blank=True)
  
    slug = models.SlugField(unique=True)
    
    created_at = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    def publish(self):
        self.created_at = timezone.now()
        self.save()

    def __int__(self):
        return self.id

apps/project/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView
from .models import Project

class ProjectIndexView(ListView):
	template_name      ='project/index.html'
	context_object_name='project'
	model=Project
	context={}
	
	def get(self, request):
		self.context['projects']= self.model.objects.all().order_by('-created_at')

		return render(request, self.template_name, self.context)

class ProjectDetailView(DetailView):
	template_name      ='project/detail.html'
	context_object_name='project'
	model=Project
	context={}

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context

apps/project/templates/project/detail.html
{% extends 'layout.html' %}

{% block title %}{{project.title}}{% endblock %}

{% block header %}
<header style="background-color:#ef2f73;width:100vw;height:60vh;display:flex;flex-direction:column;align-items:center;" class="main pymd bdb">
	<h2 style="font-size:28pt;color:rgba(255,255,255,.9);">{{project.brandname}}.</h2>
	<div style="margin-top:50px;display:flex;flex-direction:column;align-items:center;">
		<p style="font-size:18pt;color:rgba(255,255,255,.9);text-align:center;" class="wrapper768">{{ project.recap }}</p>
	</div>
</header>
{% endblock %}

{% block main %}
<main class="container">
	<div style="display:flex;flex-direction:row;justify-content:center;margin-top:-75px;">
	{% for mockup in project.mockups.all %}
	<div class="col" style="padding:0 25px;">
		<img width=175 height=340 src="{{MEDIA_URL}}{{mockup.source.url}}" alt="" />
	</div>
	{% endfor %}
	</div>
</main>
{% endblock %}

apps/project/templates/project/index.html
{% extends 'layout.html' %}

{% block title %}Projects{% endblock %}

{% block header %}
<header class="main pymd bg-blue-light bdb flex justify-center">
	<h1 class="wrapper768">Projects</h1>
</header>
{% endblock %}

{% block main %}
<main>
	<section class="flex-column align-center pysm">
		{% for project in projects %}
		<article class="wrapper768 pysm">
			<a class="col-4" href="{% url 'project:detail' slug=project.slug %}"><img style="width:100px;height:100px;" src="{{MEDIA_URL}}{{project.brandlogo.url}}" alt="{{project.slug}}" /></a>
			<section class="col-8">
				<a href="{% url 'project:detail' slug=project.slug %}">
					<h1 class="title">{{project.title}}</h1>
					<p class="desc">{{project.description}}</p>
				</a>
				{% if project.updated_at %}
				<p class="desc">{{project.updated_at}}</p>
				{% endif %}
				{% if project.tags.names %}
				<p class="desc sm highlight">Tags: {{project.tags.names|join:", "}}</p>
				{% endif %}
			</section>
		</article>
		<div class="wrapper768 pysm">
			<hr class="line"><hr class="circle">
		</div>
		{% empty %}
		{% endfor %}
	</section>
</main>
{% endblock %}